[package]
authors = ["Olle Wreede <olle@wreede.se>"]
edition = "2021"
name = "bunner-macroquad"
version = "0.1.0"

[dependencies]
macroquad = "0.3.23"

[profile.dev.package.'*']
opt-level = 3

[profile.release]
opt-level = 'z'
lto = true
panic = 'abort'
codegen-units = 1
